anuario/accounts/urls.py
from django.conf.urls import include, url
from anuario.accounts.views import (
    add_account,
    login_account,
    edit_account,
    del_account,
    request_pass_account,
    new_pass_account,
    logout_account
)
urlpatterns = [
    url(r'^nova', add_account, name='novo'),
    url(r'^entrar', login_account, name='entrar'),
    url(r'^editar', edit_account, name='editar'),
    url(r'^apagar', del_account, name='apagar'),
    #url(r'^solicitar-senha', request_pass_account, name='solicitar-senha'),
    #url(r'^solicitar-senha/$', 'django.contrib.auth.views.password_change', name='solicitar-senha'),
    #url(r'^solicitar-senha/feito$', 'django.contrib.auth.views.password_reset_done', name='nova-senha-feito'),
    #url(r'^solicitar-senha/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
    #    'django.contrib.auth.views.password_reset_confirm',
    #    name='confirme-nova-senha'),
    #url(r'^solicitar-senha/completo$', 'django.contrib.auth.views.password_reset_complete', name='nova-senha-completa'),
    #url(r'^nova-senha/$', 'django.contrib.auth.views.password_reset_complete'),
    url(r'^sair', logout_account, name='sair'),
]

anuario/core/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

anuario/pesquisador/urls.py
from django.conf.urls import url

from .views import todos_pesquisadores, editar_pesquisador, meu_perfil, editar_meu_perfil #, pesquisador, edit_pesquisador

urlpatterns = [

    url(r'^todos/$', todos_pesquisadores, name="todos"),
    #url(r'(?P<id_pesquisador>\[0-9]+)/$', pesquisador, name='perfil'),
    url(r'^editar/(?P<id_pesquisador>[0-9]+)/$', editar_pesquisador, name='editar'),
    url(r'^me-editar/$', editar_meu_perfil, name='meeditar'),
   	url(r'^eu/$', meu_perfil, name='perfil'),
]

anuario/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('anuario.core.urls', namespace='core')),
    url(r'^conta/', include('anuario.accounts.urls', namespace='accounts')),
    url(r'pesquisador/', include('anuario.pesquisador.urls', namespace='pesquisador')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">


      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>{% block title %}Anuário de Pesquisa{% endblock title %}</title>
    </head>

    <body>

    {% block navbar %}
    <!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><a href="{% url 'pesquisador:perfil' %}">Perfil</a></li>
  <li><a href="{% url 'pesquisador:meeditar' %}">Editar Perfil</a></li>
  <li class="divider"></li>
  <li><a href="{% url 'accounts:sair' %}">Sair</a></li>
</ul>

<div class="navbar-fixed">
<nav class="teal">
  <div class="nav-wrapper">
<div class="container"><a href="#!" class="brand-logo">Anuário</a></div>
    <ul class="right hide-on-med-and-down">
      <li><a href="{% url 'core:index' %}">Início</a></li>
    <li><a href="#">Pesquisas</a></li>
      <li><a href="{% url 'pesquisador:todos' %}">Pesquisadores</a></li>
     
  {% if user.is_authenticated %} 
      <!-- Dropdown Trigger -->
      <li><a href="sass.html">Minhas Pesquisas</a></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Bem Vindo, {{user}}<i class="material-icons right">arrow_drop_down</i></a></li>
  {% else %}
      <li><a href="{% url 'accounts:entrar' %}" data-activates="dropdown1">Entrar</a></li>
      <li><a href="{% url 'accounts:novo' %}" data-activates="dropdown1">Registre-se</a></li>
  {% endif %}

    </ul>
  </div>
</nav>
</div>
    {% endblock navbar %}

    {% block sidebar %}
    {% endblock sidebar %}

    {% block content %}
    {% endblock content %}


  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Anuário de Pesquisa da UFRPE/UAST</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Mapa do Site</h5>
          <ul>
            <li><a class="white-text" href="#!">Início</a></li>
            <li><a class="white-text" href="#!">Pesquisas</a></li>
            <li><a class="white-text" href="#!">Pesquisadores</a></li>
            <li><a class="white-text" href="#!">Contato</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Conexões</h5>
          <ul>
            <li><a class="white-text" href="#!">Facebook</a></li>
            <li><a class="white-text" href="#!">Twitter</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      <span>Desenvolvido por: </span>
     <a href="http://www.tagi.com.br/">
          <img src="http://faroldenoticias.com.br/wp-content/themes/farol-de-noticias/assets/images/tagi.png" alt="tagi"></a>
      </div>
    </div>
  </footer>


      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <!-- Compiled and minified JavaScript -->
  	  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

  	  <script type="text/javascript">
  	  		          $(document).ready(function() {

			    $('.button-collapse').sideNav();
			    $('.parallax').parallax();

      $('select').material_select();


			}); // end of document ready

  	  </script>
    </body>
  </html>